/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AppWorkspacesRouteImport } from './routes/app/workspaces'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppSecurityRouteImport } from './routes/app/security'
import { Route as AppQueryHistoryRouteImport } from './routes/app/query-history'
import { Route as AppPdfViewerRouteImport } from './routes/app/pdf-viewer'
import { Route as AppJobsRouteImport } from './routes/app/jobs'
import { Route as AppInsightsRouteImport } from './routes/app/insights'
import { Route as AppDocumentsRouteImport } from './routes/app/documents'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppBillingRouteImport } from './routes/app/billing'
import { Route as AppSearchIndexRouteImport } from './routes/app/search/index'
import { Route as AppSearchAskAiRouteImport } from './routes/app/search/ask-ai'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspacesRoute = AppWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityRoute = AppSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppRoute,
} as any)
const AppQueryHistoryRoute = AppQueryHistoryRouteImport.update({
  id: '/query-history',
  path: '/query-history',
  getParentRoute: () => AppRoute,
} as any)
const AppPdfViewerRoute = AppPdfViewerRouteImport.update({
  id: '/pdf-viewer',
  path: '/pdf-viewer',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchIndexRoute = AppSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchAskAiRoute = AppSearchAskAiRouteImport.update({
  id: '/search/ask-ai',
  path: '/search/ask-ai',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/billing': typeof AppBillingRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/pdf-viewer': typeof AppPdfViewerRoute
  '/app/query-history': typeof AppQueryHistoryRoute
  '/app/security': typeof AppSecurityRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/workspaces': typeof AppWorkspacesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app/': typeof AppIndexRoute
  '/app/search/ask-ai': typeof AppSearchAskAiRoute
  '/app/search/': typeof AppSearchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/billing': typeof AppBillingRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/pdf-viewer': typeof AppPdfViewerRoute
  '/app/query-history': typeof AppQueryHistoryRoute
  '/app/security': typeof AppSecurityRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/workspaces': typeof AppWorkspacesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app': typeof AppIndexRoute
  '/app/search/ask-ai': typeof AppSearchAskAiRoute
  '/app/search': typeof AppSearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/billing': typeof AppBillingRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/pdf-viewer': typeof AppPdfViewerRoute
  '/app/query-history': typeof AppQueryHistoryRoute
  '/app/security': typeof AppSecurityRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/workspaces': typeof AppWorkspacesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app/': typeof AppIndexRoute
  '/app/search/ask-ai': typeof AppSearchAskAiRoute
  '/app/search/': typeof AppSearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/billing'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/insights'
    | '/app/jobs'
    | '/app/pdf-viewer'
    | '/app/query-history'
    | '/app/security'
    | '/app/settings'
    | '/app/workspaces'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/app/'
    | '/app/search/ask-ai'
    | '/app/search/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/billing'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/insights'
    | '/app/jobs'
    | '/app/pdf-viewer'
    | '/app/query-history'
    | '/app/security'
    | '/app/settings'
    | '/app/workspaces'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/app'
    | '/app/search/ask-ai'
    | '/app/search'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/billing'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/insights'
    | '/app/jobs'
    | '/app/pdf-viewer'
    | '/app/query-history'
    | '/app/security'
    | '/app/settings'
    | '/app/workspaces'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/app/'
    | '/app/search/ask-ai'
    | '/app/search/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workspaces': {
      id: '/app/workspaces'
      path: '/workspaces'
      fullPath: '/app/workspaces'
      preLoaderRoute: typeof AppWorkspacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/security': {
      id: '/app/security'
      path: '/security'
      fullPath: '/app/security'
      preLoaderRoute: typeof AppSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/query-history': {
      id: '/app/query-history'
      path: '/query-history'
      fullPath: '/app/query-history'
      preLoaderRoute: typeof AppQueryHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pdf-viewer': {
      id: '/app/pdf-viewer'
      path: '/pdf-viewer'
      fullPath: '/app/pdf-viewer'
      preLoaderRoute: typeof AppPdfViewerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/jobs': {
      id: '/app/jobs'
      path: '/jobs'
      fullPath: '/app/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/insights': {
      id: '/app/insights'
      path: '/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/search/': {
      id: '/app/search/'
      path: '/search'
      fullPath: '/app/search/'
      preLoaderRoute: typeof AppSearchIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/search/ask-ai': {
      id: '/app/search/ask-ai'
      path: '/search/ask-ai'
      fullPath: '/app/search/ask-ai'
      preLoaderRoute: typeof AppSearchAskAiRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppJobsRoute: typeof AppJobsRoute
  AppPdfViewerRoute: typeof AppPdfViewerRoute
  AppQueryHistoryRoute: typeof AppQueryHistoryRoute
  AppSecurityRoute: typeof AppSecurityRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWorkspacesRoute: typeof AppWorkspacesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSearchAskAiRoute: typeof AppSearchAskAiRoute
  AppSearchIndexRoute: typeof AppSearchIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppJobsRoute: AppJobsRoute,
  AppPdfViewerRoute: AppPdfViewerRoute,
  AppQueryHistoryRoute: AppQueryHistoryRoute,
  AppSecurityRoute: AppSecurityRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWorkspacesRoute: AppWorkspacesRoute,
  AppIndexRoute: AppIndexRoute,
  AppSearchAskAiRoute: AppSearchAskAiRoute,
  AppSearchIndexRoute: AppSearchIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
